"use client";

import { useState, useEffect } from "react";
import { Zap, Copy, Check, ChevronDown, ChevronUp, Github } from "lucide-react";
import { useSession } from "next-auth/react";

const BACKEND_URL = "https://repo2viral-backend.onrender.com";

function CodeBlock({ code, filename }: { code: string; filename: string }) {
    const [copied, setCopied] = useState(false);
    const copy = async () => {
        await navigator.clipboard.writeText(code);
        setCopied(true);
        setTimeout(() => setCopied(false), 1800);
    };
    return (
        <div className="rounded-xl overflow-hidden border border-slate-700">
            <div className="bg-slate-800 px-4 py-2 flex items-center justify-between">
                <span className="text-xs font-mono text-slate-400">{filename}</span>
                <button
                    onClick={copy}
                    className="flex items-center gap-1.5 text-xs text-slate-400 hover:text-white transition-colors"
                >
                    {copied ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
                    {copied ? "Copied" : "Copy"}
                </button>
            </div>
            <pre className="bg-slate-950 p-4 text-xs text-slate-300 font-mono overflow-x-auto leading-relaxed">
                <code>{code}</code>
            </pre>
        </div>
    );
}

function Step({ n, title, children }: { n: number; title: string; children: React.ReactNode }) {
    const [open, setOpen] = useState(n === 1);
    return (
        <div className="border border-slate-800 rounded-xl overflow-hidden">
            <button
                onClick={() => setOpen((o) => !o)}
                className="w-full flex items-center gap-4 p-5 text-left hover:bg-slate-800/50 transition-colors"
            >
                <span className="w-7 h-7 rounded-full bg-indigo-600 text-white text-sm font-bold flex items-center justify-center shrink-0">{n}</span>
                <span className="font-medium text-white flex-1">{title}</span>
                {open ? <ChevronUp className="w-4 h-4 text-slate-500" /> : <ChevronDown className="w-4 h-4 text-slate-500" />}
            </button>
            {open && <div className="px-5 pb-5 space-y-4 border-t border-slate-800 pt-4">{children}</div>}
        </div>
    );
}

export default function GitHubActionPage() {
    const { data: session } = useSession();
    const userId = (session as any)?.userId || session?.user?.id || "YOUR_USER_ID";

    const actionYaml = `name: 🚀 Repo2Viral — Auto Generate on Release

on:
  release:
    types: [published]
  workflow_dispatch:   # also run manually from Actions tab

jobs:
  generate-viral-content:
    runs-on: ubuntu-latest
    name: Generate viral thread & post to release

    steps:
      - name: Call Repo2Viral API
        id: r2v
        run: |
          RESPONSE=$(curl -sf -X POST ${BACKEND_URL}/analyze \\
            -H "Content-Type: application/json" \\
            -d '{
              "url":     "https://github.com/\${{ github.repository }}",
              "user_id": "\${{ secrets.REPO2VIRAL_USER_ID }}",
              "email":   "\${{ secrets.REPO2VIRAL_EMAIL }}",
              "tone":    "Hype Man"
            }')

          # Extract the twitter_thread field
          THREAD=$(echo "$RESPONSE" | python3 -c \\
            "import sys,json; d=json.load(sys.stdin); print(d.get('twitter_thread','Generation failed — check secrets.'))" \\
          )

          # Save for next step (multiline safe)
          echo "THREAD<<__EOF__" >> \$GITHUB_OUTPUT
          echo "$THREAD"         >> \$GITHUB_OUTPUT
          echo "__EOF__"         >> \$GITHUB_OUTPUT

      - name: Append thread to release notes
        uses: actions/github-script@v7
        with:
          script: |
            const thread = \`\${{ steps.r2v.outputs.THREAD }}\`;
            const section = [
              '',
              '---',
              '## 🚀 Repo2Viral — Twitter Thread',
              '',
              'Copy and paste this thread to announce the release:',
              '',
              '\`\`\`',
              thread,
              '\`\`\`',
              '',
              '*Generated by [Repo2Viral](https://repo2viral.com)*',
            ].join('\\n');

            const release = await github.rest.repos.getRelease({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              release_id: context.payload.release?.id ?? 0,
            });

            await github.rest.repos.updateRelease({
              owner:      context.repo.owner,
              repo:       context.repo.repo,
              release_id: release.data.id,
              body:       (release.data.body ?? '') + section,
            });
`;

    return (
        <div className="space-y-8 animate-fade-in-up max-w-3xl">
            <div>
                <h1 className="text-3xl font-bold text-white mb-2 flex items-center gap-3">
                    <Zap className="w-7 h-7 text-yellow-400" />
                    GitHub Action
                </h1>
                <p className="text-slate-400">
                    Auto-generate a viral Twitter thread every time you publish a release. Install once — content forever.
                </p>
            </div>

            {/* How it works banner */}
            <div className="grid grid-cols-3 gap-4 text-center">
                {[
                    { icon: "📦", label: "Publish release", sub: "on GitHub" },
                    { icon: "⚡", label: "Action triggers", sub: "calls Repo2Viral API" },
                    { icon: "🧵", label: "Thread appended", sub: "to your release notes" },
                ].map((item, i) => (
                    <div key={i} className="bg-slate-900 border border-slate-800 rounded-xl p-4">
                        <div className="text-2xl mb-1">{item.icon}</div>
                        <p className="text-sm font-semibold text-white">{item.label}</p>
                        <p className="text-xs text-slate-500 mt-0.5">{item.sub}</p>
                    </div>
                ))}
            </div>

            {/* Step-by-step */}
            <div className="space-y-3">
                <Step n={1} title="Add the workflow file to your repository">
                    <p className="text-sm text-slate-400">
                        Create the file <code className="text-indigo-300 bg-indigo-950/40 px-1.5 py-0.5 rounded text-xs">.github/workflows/repo2viral.yml</code> in your repo with this content:
                    </p>
                    <CodeBlock code={actionYaml} filename=".github/workflows/repo2viral.yml" />
                </Step>

                <Step n={2} title="Add your Repo2Viral credentials as GitHub Secrets">
                    <p className="text-sm text-slate-400 mb-3">
                        Go to your repo → <strong className="text-white">Settings → Secrets and variables → Actions → New repository secret</strong>.
                        Add these two secrets:
                    </p>
                    <div className="space-y-3">
                        <div className="bg-slate-950 border border-slate-700 rounded-xl p-4 space-y-3">
                            <div className="flex items-center justify-between gap-4">
                                <div>
                                    <code className="text-yellow-300 text-sm font-mono">REPO2VIRAL_USER_ID</code>
                                    <p className="text-xs text-slate-500 mt-0.5">Your unique Repo2Viral user ID</p>
                                </div>
                                <code className="text-xs font-mono bg-slate-800 px-3 py-1.5 rounded-lg text-indigo-300 shrink-0">{userId}</code>
                            </div>
                            <div className="flex items-center justify-between gap-4">
                                <div>
                                    <code className="text-yellow-300 text-sm font-mono">REPO2VIRAL_EMAIL</code>
                                    <p className="text-xs text-slate-500 mt-0.5">The email linked to your account</p>
                                </div>
                                <code className="text-xs font-mono bg-slate-800 px-3 py-1.5 rounded-lg text-indigo-300 shrink-0">your@email.com</code>
                            </div>
                        </div>
                    </div>
                </Step>

                <Step n={3} title="Publish a release to trigger it">
                    <p className="text-sm text-slate-400">
                        Go to <strong className="text-white">Releases → Draft a new release → Publish release</strong>.
                        The Action will run automatically and append a formatted Twitter thread to your release notes within ~30 seconds.
                    </p>
                    <p className="text-sm text-slate-400">
                        You can also trigger it manually from the <strong className="text-white">Actions</strong> tab using <em>workflow_dispatch</em>.
                    </p>
                </Step>
            </div>

            <div className="bg-yellow-500/5 border border-yellow-500/20 rounded-xl p-4 flex items-start gap-3">
                <Github className="w-4 h-4 text-yellow-400 mt-0.5 shrink-0" />
                <p className="text-sm text-slate-400">
                    <span className="text-yellow-400 font-medium">Free tier note:</span> The Action uses your Repo2Viral account quota (5 generations/month on Free). Upgrade to Pro for unlimited generations — unlimited repos, unlimited releases.
                </p>
            </div>
        </div>
    );
}
