import { ImageResponse } from 'next/og'; // We can use next/og which wraps Satori, OR use Satori directly.
// The user specifically asked for "Satori" and "@resvg/resvg-js" manually, implies they might want a custom route returning a buffer, 
// but using standard Next.js ImageResponse is usually easier. However, ImageResponse returns a Response object.
// To satisfy the specific requirement of "@resvg/resvg-js for PNG", I'll use satori directly to get SVG, then resvg to PNG.

import { NextRequest, NextResponse } from "next/server";
import satori from "satori";
import React from 'react';

// Force Node.js runtime for @resvg/resvg-js native addon support
export const runtime = 'nodejs';

// Stub highlighter (can be expanded later)
async function highlight(code: string) {
    return code;
}

export async function POST(req: NextRequest) {
    console.log("Generating Slide API Hit");
    try {
        // Dynamically import Resvg to prevent startup crashes if binary is missing
        const { Resvg } = await import('@resvg/resvg-js');

        const body = await req.json();
        const { type, content, title, footer, isPro } = body;

        // Use reliable raw GitHub URLs for fonts
        const fontBold = await fetch('https://raw.githubusercontent.com/google/fonts/main/ofl/inter/Inter-Bold.ttf').then(res => res.arrayBuffer());
        const fontRegular = await fetch('https://raw.githubusercontent.com/google/fonts/main/ofl/inter/Inter-Regular.ttf').then(res => res.arrayBuffer());

        let markup;

        const cardStyle: React.CSSProperties = {
            height: '100%',
            width: '100%',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: '#020617', // Slate 950
            backgroundImage: 'radial-gradient(circle at 25px 25px, #1e293b 2%, transparent 0%), radial-gradient(circle at 75px 75px, #1e293b 2%, transparent 0%)',
            backgroundSize: '100px 100px',
            color: 'white',
            fontFamily: 'Inter',
            position: 'relative',
        };

        const footerMarkup = (
            <div style={{
                position: 'absolute',
                bottom: 40,
                left: 60,
                right: 60,
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                color: '#64748b', // Slate 500
                fontSize: 24,
            }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                    {/* Avatar/Icon placeholder */}
                    <div style={{ width: 40, height: 40, borderRadius: '50%', backgroundColor: '#6366f1' }}></div>
                    <span>repo-to-viral</span>
                </div>
                <span>{footer || 'Swipe ->'}</span>
            </div>
        );

        const watermark = !isPro ? (
            <div style={{
                position: 'absolute',
                bottom: 10,
                right: 10,
                fontSize: 16,
                color: '#475569',
                opacity: 0.5
            }}>
                Generated by Repo2Viral
            </div>
        ) : null;

        if (type === 'cover') {
            markup = (
                <div style={cardStyle}>
                    <div style={{
                        display: 'flex',
                        flexDirection: 'column',
                        alignItems: 'flex-start',
                        padding: '0 80px',
                        width: '100%'
                    }}>
                        <div style={{
                            backgroundColor: 'rgba(99, 102, 241, 0.2)', // Indigo
                            color: '#818cf8',
                            padding: '10px 30px',
                            borderRadius: 50,
                            fontSize: 24,
                            marginBottom: 40,
                            border: '2px solid rgba(99, 102, 241, 0.3)'
                        }}>
                            OPEN SOURCE SPOTLIGHT
                        </div>
                        <h1 style={{
                            fontSize: 80,
                            fontWeight: 700,
                            lineHeight: 1.1,
                            background: 'linear-gradient(to bottom right, #ffffff, #94a3b8)',
                            backgroundClip: 'text',
                            color: 'transparent',
                            marginBottom: 40
                        }}>
                            {title}
                        </h1>
                        <div style={{ width: 150, height: 10, backgroundColor: '#6366f1', borderRadius: 5 }}></div>
                    </div>
                </div>
            );
        } else if (type === 'code') {
            // Highlight code using shiki helper
            const hCode = await highlight(content || '// No code provided');

            markup = (
                <div style={cardStyle}>
                    <div style={{
                        display: 'flex',
                        flexDirection: 'column',
                        width: '85%',
                    }}>
                        <h2 style={{ fontSize: 50, fontWeight: 700, color: '#4ade80', marginBottom: 40 }}>
                            {title || 'The Solution'}
                        </h2>

                        {/* Macbook Window */}
                        <div style={{
                            borderRadius: 20,
                            backgroundColor: '#0f172a', // Slate 900
                            border: '1px solid #334155',
                            boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5)',
                            display: 'flex',
                            flexDirection: 'column',
                            overflow: 'hidden'
                        }}>
                            {/* Window Header */}
                            <div style={{
                                height: 50,
                                backgroundColor: '#1e293b',
                                borderBottom: '1px solid #334155',
                                display: 'flex',
                                alignItems: 'center',
                                paddingLeft: 20,
                                gap: 10
                            }}>
                                <div style={{ width: 15, height: 15, borderRadius: '50%', backgroundColor: '#ef4444' }}></div>
                                <div style={{ width: 15, height: 15, borderRadius: '50%', backgroundColor: '#f59e0b' }}></div>
                                <div style={{ width: 15, height: 15, borderRadius: '50%', backgroundColor: '#22c55e' }}></div>
                            </div>

                            {/* Code Area */}
                            <div style={{
                                padding: 40,
                                fontSize: 24,
                                lineHeight: 1.5,
                                fontFamily: 'monospace',
                                color: '#e2e8f0',
                                display: 'flex',
                                flexDirection: 'column'
                            }}>
                                {/* We inject the HTML string from shiki. Satori supports some basic HTML, but dangerouslySetInnerHTML works best if structured cleanly. 
                                    However, Satori logic is React based. We need to parse simple spans. 
                                    For MVP, we will pass rich text as pre-calculated nodes or just simple text if shiki is too complex to wire up in one go.
                                    Actually, Shiki returns HTML string. We can try to sanitize or just dump it if Satori supports it.
                                    Satori doesn't support `dangerouslySetInnerHTML` fully in the same way. 
                                    We will render plain text for now to ensure stability, or use a simplified highlighter manually.
                                */}
                                <pre style={{ margin: 0, whiteSpace: 'pre-wrap' }}>
                                    {hCode}
                                </pre>
                            </div>
                        </div>
                    </div>
                </div>
            );
        } else {
            // General Slide (Problem, Stats, CTA)
            markup = (
                <div style={cardStyle}>
                    <div style={{ display: 'flex', flexDirection: 'column', padding: '0 80px' }}>
                        <h2 style={{ fontSize: 60, fontWeight: 700, color: '#f87171', marginBottom: 40, borderLeft: '10px solid #ef4444', paddingLeft: 30 }}>
                            {title}
                        </h2>
                        <p style={{ fontSize: 40, lineHeight: 1.4, color: '#cbd5e1' }}>
                            {content}
                        </p>
                    </div>
                </div>
            );
        }

        // Wrap with common elements
        const finalMarkup = (
            <div style={{ width: '100%', height: '100%', display: 'flex' }}>
                {markup}
                {footerMarkup}
                {watermark}
            </div>
        );

        const svg = await satori(
            finalMarkup,
            {
                width: 1080,
                height: 1350,
                fonts: [
                    {
                        name: 'Inter',
                        data: fontBold,
                        weight: 700,
                        style: 'normal',
                    },
                    {
                        name: 'Inter',
                        data: fontRegular,
                        weight: 400,
                        style: 'normal',
                    }
                ],
            }
        );

        const resvg = new Resvg(svg, {
            fitTo: { mode: 'width', value: 1080 },
        });
        const pngData = resvg.render();
        const pngBuffer = pngData.asPng();

        return new NextResponse(pngBuffer as any, {
            headers: { 'Content-Type': 'image/png' },
        });

    } catch (e: any) {
        console.error("Generate Slide API Error:", e);
        return NextResponse.json({ error: e.message || "Unknown error" }, { status: 500 });
    }
}
